export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT';

export const CHAT_QUIT = 'CHAT_QUIT';
export const JOIN_SUCCESS = 'JOIN_SUCCESS';
export const USER_CONNECTED = 'USER_CONNECTED';
export const USER_DISCONNECTED = 'USER_DISCONNECTED';

export const MESSAGE_SEND = 'MESSAGE_SEND';
export const MESSAGE_RECEIVE = 'MESSAGE_RECEIVE';
export const MESSAGE_RECEIVED_BY_SERVER = 'MESSAGE_RECEIVED_BY_SERVER';

export const DIALOG_RESTORE = 'DIALOG_RESTORE';
export const DIALOG_READ = 'DIALOG_READ';
